name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to project folder
        run: cd "02 Starting Project"

      - name: Verify package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to project folder
        run: cd "02 Starting Project"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            02 Starting Project/dist
            02 Starting Project/package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Navigate to project folder
        run: cd "02 Starting Project"

      - name: Deploy
        run: echo "Deploying..."
