name: Test Project

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Get Code repository
        uses: actions/checkout@v4
      
      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify a stable Node.js version
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 4: Run tests
      - name: Run tests
        run: npm 
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
        # Step 1: Check out the code
      - name: Get Code repository
        uses: actions/checkout@v4
      
      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify a stable Node.js version
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 4: Run tests
      - name: Run tests
        run: npm 

